#!/usr/bin/env python3
"""Download and extract the official 10K Synthea COVID-19 CSV benchmark.

The archive is deliberately excluded from Git. This command preserves a source
receipt and checksum so another reviewer can reproduce and verify the input.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
import urllib.request
import zipfile
from pathlib import Path

SOURCE_URL = (
    "https://github.com/synthetichealth/synthea-sample-data/raw/main/"
    "downloads/10k_synthea_covid19_csv.zip"
)
USER_AGENT = "clinical-documentation-copilot/1.0 (research benchmark downloader)"
EVIDENCE_SNAPSHOT_AT = "2026-04-18T17:00:00+00:00"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def download(url: str, destination: Path, force: bool) -> None:
    if destination.exists() and not force:
        print(f"Using existing archive: {destination}")
        return
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_suffix(destination.suffix + ".part")
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=120) as response, temporary.open("wb") as out:
        shutil.copyfileobj(response, out, length=1024 * 1024)
    temporary.replace(destination)


def safe_extract(archive: Path, destination: Path) -> list[str]:
    destination.mkdir(parents=True, exist_ok=True)
    extracted: list[str] = []
    root = destination.resolve()
    with zipfile.ZipFile(archive) as bundle:
        for member in bundle.infolist():
            target = (destination / member.filename).resolve()
            if root not in target.parents and target != root:
                raise ValueError(f"Unsafe archive path: {member.filename}")
            bundle.extract(member, destination)
            if not member.is_dir():
                extracted.append(member.filename)
    return extracted


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--url", default=SOURCE_URL)
    args = parser.parse_args()

    archive = args.root / "data" / "raw" / "10k_synthea_covid19_csv.zip"
    destination = args.root / "data" / "raw" / "synthea-covid19-10k"
    receipt_path = args.root / "evidence" / "dataset" / "source_receipt.json"

    try:
        download(args.url, archive, args.force)
        files = safe_extract(archive, destination)
    except Exception as exc:  # explicit CLI error boundary
        print(f"Dataset preparation failed: {exc}", file=sys.stderr)
        return 1

    receipt = {
        "source": "MITRE Synthea official sample-data repository",
        "source_url": args.url,
        "source_page": "https://synthea.mitre.org/downloads",
        "archive": archive.name,
        "archive_bytes": archive.stat().st_size,
        "archive_sha256": sha256(archive),
        "evidence_snapshot_at_utc": EVIDENCE_SNAPSHOT_AT,
        "synthetic_data_only": True,
        "restricted_data_included": False,
        "extracted_file_count": len(files),
        "extraction_directory": str(destination.relative_to(args.root)),
        "license_note": "Generated by Apache-2.0 Synthea; see upstream notices.",
    }
    receipt_path.parent.mkdir(parents=True, exist_ok=True)
    receipt_path.write_text(json.dumps(receipt, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(receipt, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
